import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import Navbar from "@/components/shared/navbar";
import { ReduxProvider } from "@/store/provider";

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: `REST Countries API`,
  description: "Generated by Karim Ayman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunitoSans.variable} min-h-screen flex flex-col gap-10
        bg-very-light-dark-gray dark:bg-dark-bg text-light-mode-text dark:text-very-light-dark-gray`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReduxProvider>
            <Navbar />
            {children}
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
